"""
AI Response Models
===================
Pydantic models for structured AI responses.

These models ensure type safety and validation for AI-generated content.
"""
from typing import Optional

from pydantic import BaseModel, Field


class OrganizationSuggestion(BaseModel):
    """Suggested file organization in Johnny.Decimal structure.
    
    Represents an AI-generated suggestion for where a file
    should be placed within the DevBase workspace hierarchy.
    
    Attributes:
        destination: Target path within workspace (e.g., "20-29_CODE/21_apps").
        new_name: Suggested filename if renaming is recommended.
        confidence: AI confidence in this suggestion (0.0-1.0).
        reasoning: Explanation of why this destination was chosen.
    """
    
    destination: str = Field(
        ...,
        description="Suggested destination path within Johnny.Decimal structure",
        examples=["20-29_CODE/21_apps/project-name"],
    )
    new_name: Optional[str] = Field(
        default=None,
        description="Suggested new filename (if renaming recommended)",
        examples=["fastapi-best-practices-2024-12.md"],
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score from 0.0 (uncertain) to 1.0 (certain)",
    )
    reasoning: str = Field(
        ...,
        min_length=10,
        description="Explanation of why this organization was suggested",
    )


class Insight(BaseModel):
    """Workspace insight generated by AI analysis.
    
    Represents a single observation or recommendation about
    the workspace structure, organization, or usage patterns.
    
    Attributes:
        category: Type of insight (architecture, optimization, organization).
        title: Brief summary of the insight.
        description: Detailed explanation and recommendations.
        severity: Importance level (info, suggestion, warning).
    """
    
    category: str = Field(
        ...,
        description="Insight category",
        pattern="^(architecture|optimization|organization)$",
    )
    title: str = Field(
        ...,
        min_length=5,
        max_length=100,
        description="Brief summary of the insight",
    )
    description: str = Field(
        ...,
        min_length=20,
        description="Detailed explanation and actionable recommendations",
    )
    severity: str = Field(
        ...,
        description="Importance level",
        pattern="^(info|suggestion|warning)$",
    )


class WorkspaceAnalysis(BaseModel):
    """Complete workspace analysis result.
    
    Contains the overall health score and list of insights
    generated from AI analysis of a workspace.
    
    Attributes:
        score: Overall organization score (0-100).
        insights: List of individual insights.
    """
    
    score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Overall workspace organization score",
    )
    insights: list[Insight] = Field(
        default_factory=list,
        description="List of insights from the analysis",
    )
